package main

import (
	"github.com/aws-single-sign-on-admin/mcp-server/config"
	"github.com/aws-single-sign-on-admin/mcp-server/models"
	tools_x_amz_target_swbexternalservice_listaccountassignmentcreationstatus "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_listaccountassignmentcreationstatus"
	tools_x_amz_target_swbexternalservice_attachmanagedpolicytopermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_attachmanagedpolicytopermissionset"
	tools_x_amz_target_swbexternalservice_deletepermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_deletepermissionset"
	tools_x_amz_target_swbexternalservice_updatepermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_updatepermissionset"
	tools_x_amz_target_swbexternalservice_listinstances "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_listinstances"
	tools_x_amz_target_swbexternalservice_deleteinstanceaccesscontrolattributeconfiguration "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_deleteinstanceaccesscontrolattributeconfiguration"
	tools_x_amz_target_swbexternalservice_putpermissionsboundarytopermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_putpermissionsboundarytopermissionset"
	tools_x_amz_target_swbexternalservice_detachmanagedpolicyfrompermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_detachmanagedpolicyfrompermissionset"
	tools_x_amz_target_swbexternalservice_listcustomermanagedpolicyreferencesinpermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_listcustomermanagedpolicyreferencesinpermissionset"
	tools_x_amz_target_swbexternalservice_listpermissionsetsprovisionedtoaccount "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_listpermissionsetsprovisionedtoaccount"
	tools_x_amz_target_swbexternalservice_describepermissionsetprovisioningstatus "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_describepermissionsetprovisioningstatus"
	tools_x_amz_target_swbexternalservice_createaccountassignment "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_createaccountassignment"
	tools_x_amz_target_swbexternalservice_describeaccountassignmentdeletionstatus "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_describeaccountassignmentdeletionstatus"
	tools_x_amz_target_swbexternalservice_listaccountassignments "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_listaccountassignments"
	tools_x_amz_target_swbexternalservice_listpermissionsets "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_listpermissionsets"
	tools_x_amz_target_swbexternalservice_listmanagedpoliciesinpermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_listmanagedpoliciesinpermissionset"
	tools_x_amz_target_swbexternalservice_getinlinepolicyforpermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_getinlinepolicyforpermissionset"
	tools_x_amz_target_swbexternalservice_listpermissionsetprovisioningstatus "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_listpermissionsetprovisioningstatus"
	tools_x_amz_target_swbexternalservice_listtagsforresource "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_listtagsforresource"
	tools_x_amz_target_swbexternalservice_deleteaccountassignment "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_deleteaccountassignment"
	tools_x_amz_target_swbexternalservice_describepermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_describepermissionset"
	tools_x_amz_target_swbexternalservice_listaccountassignmentdeletionstatus "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_listaccountassignmentdeletionstatus"
	tools_x_amz_target_swbexternalservice_untagresource "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_untagresource"
	tools_x_amz_target_swbexternalservice_getpermissionsboundaryforpermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_getpermissionsboundaryforpermissionset"
	tools_x_amz_target_swbexternalservice_attachcustomermanagedpolicyreferencetopermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_attachcustomermanagedpolicyreferencetopermissionset"
	tools_x_amz_target_swbexternalservice_deletepermissionsboundaryfrompermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_deletepermissionsboundaryfrompermissionset"
	tools_x_amz_target_swbexternalservice_describeaccountassignmentcreationstatus "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_describeaccountassignmentcreationstatus"
	tools_x_amz_target_swbexternalservice_createinstanceaccesscontrolattributeconfiguration "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_createinstanceaccesscontrolattributeconfiguration"
	tools_x_amz_target_swbexternalservice_describeinstanceaccesscontrolattributeconfiguration "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_describeinstanceaccesscontrolattributeconfiguration"
	tools_x_amz_target_swbexternalservice_tagresource "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_tagresource"
	tools_x_amz_target_swbexternalservice_putinlinepolicytopermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_putinlinepolicytopermissionset"
	tools_x_amz_target_swbexternalservice_updateinstanceaccesscontrolattributeconfiguration "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_updateinstanceaccesscontrolattributeconfiguration"
	tools_x_amz_target_swbexternalservice_detachcustomermanagedpolicyreferencefrompermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_detachcustomermanagedpolicyreferencefrompermissionset"
	tools_x_amz_target_swbexternalservice_provisionpermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_provisionpermissionset"
	tools_x_amz_target_swbexternalservice_deleteinlinepolicyfrompermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_deleteinlinepolicyfrompermissionset"
	tools_x_amz_target_swbexternalservice_listaccountsforprovisionedpermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_listaccountsforprovisionedpermissionset"
	tools_x_amz_target_swbexternalservice_createpermissionset "github.com/aws-single-sign-on-admin/mcp-server/tools/x_amz_target_swbexternalservice_createpermissionset"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_swbexternalservice_listaccountassignmentcreationstatus.CreateListaccountassignmentcreationstatusTool(cfg),
		tools_x_amz_target_swbexternalservice_attachmanagedpolicytopermissionset.CreateAttachmanagedpolicytopermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_deletepermissionset.CreateDeletepermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_updatepermissionset.CreateUpdatepermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_listinstances.CreateListinstancesTool(cfg),
		tools_x_amz_target_swbexternalservice_deleteinstanceaccesscontrolattributeconfiguration.CreateDeleteinstanceaccesscontrolattributeconfigurationTool(cfg),
		tools_x_amz_target_swbexternalservice_putpermissionsboundarytopermissionset.CreatePutpermissionsboundarytopermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_detachmanagedpolicyfrompermissionset.CreateDetachmanagedpolicyfrompermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_listcustomermanagedpolicyreferencesinpermissionset.CreateListcustomermanagedpolicyreferencesinpermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_listpermissionsetsprovisionedtoaccount.CreateListpermissionsetsprovisionedtoaccountTool(cfg),
		tools_x_amz_target_swbexternalservice_describepermissionsetprovisioningstatus.CreateDescribepermissionsetprovisioningstatusTool(cfg),
		tools_x_amz_target_swbexternalservice_createaccountassignment.CreateCreateaccountassignmentTool(cfg),
		tools_x_amz_target_swbexternalservice_describeaccountassignmentdeletionstatus.CreateDescribeaccountassignmentdeletionstatusTool(cfg),
		tools_x_amz_target_swbexternalservice_listaccountassignments.CreateListaccountassignmentsTool(cfg),
		tools_x_amz_target_swbexternalservice_listpermissionsets.CreateListpermissionsetsTool(cfg),
		tools_x_amz_target_swbexternalservice_listmanagedpoliciesinpermissionset.CreateListmanagedpoliciesinpermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_getinlinepolicyforpermissionset.CreateGetinlinepolicyforpermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_listpermissionsetprovisioningstatus.CreateListpermissionsetprovisioningstatusTool(cfg),
		tools_x_amz_target_swbexternalservice_listtagsforresource.CreateListtagsforresourceTool(cfg),
		tools_x_amz_target_swbexternalservice_deleteaccountassignment.CreateDeleteaccountassignmentTool(cfg),
		tools_x_amz_target_swbexternalservice_describepermissionset.CreateDescribepermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_listaccountassignmentdeletionstatus.CreateListaccountassignmentdeletionstatusTool(cfg),
		tools_x_amz_target_swbexternalservice_untagresource.CreateUntagresourceTool(cfg),
		tools_x_amz_target_swbexternalservice_getpermissionsboundaryforpermissionset.CreateGetpermissionsboundaryforpermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_attachcustomermanagedpolicyreferencetopermissionset.CreateAttachcustomermanagedpolicyreferencetopermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_deletepermissionsboundaryfrompermissionset.CreateDeletepermissionsboundaryfrompermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_describeaccountassignmentcreationstatus.CreateDescribeaccountassignmentcreationstatusTool(cfg),
		tools_x_amz_target_swbexternalservice_createinstanceaccesscontrolattributeconfiguration.CreateCreateinstanceaccesscontrolattributeconfigurationTool(cfg),
		tools_x_amz_target_swbexternalservice_describeinstanceaccesscontrolattributeconfiguration.CreateDescribeinstanceaccesscontrolattributeconfigurationTool(cfg),
		tools_x_amz_target_swbexternalservice_tagresource.CreateTagresourceTool(cfg),
		tools_x_amz_target_swbexternalservice_putinlinepolicytopermissionset.CreatePutinlinepolicytopermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_updateinstanceaccesscontrolattributeconfiguration.CreateUpdateinstanceaccesscontrolattributeconfigurationTool(cfg),
		tools_x_amz_target_swbexternalservice_detachcustomermanagedpolicyreferencefrompermissionset.CreateDetachcustomermanagedpolicyreferencefrompermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_provisionpermissionset.CreateProvisionpermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_deleteinlinepolicyfrompermissionset.CreateDeleteinlinepolicyfrompermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_listaccountsforprovisionedpermissionset.CreateListaccountsforprovisionedpermissionsetTool(cfg),
		tools_x_amz_target_swbexternalservice_createpermissionset.CreateCreatepermissionsetTool(cfg),
	}
}
